config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages', to: 'pages#index'
  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: %i[new create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
# frozen_string_literal: true

class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
# frozen_string_literal: true

class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :ingredient, presence: true, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
# frozen_string_literal: true

class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show]
  def index
    @cocktails = Cocktail.all
  end

  def show; end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
# frozen_string_literal: true

class DosesController < ApplicationController
  before_action :find_cocktail, only: %i[new create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cocktails_helper.rb
# frozen_string_literal: true

module CocktailsHelper
end

app/helpers/doses_helper.rb
# frozen_string_literal: true

module DosesHelper
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/cocktails/_banner.html.erb
<div class="main">
  <div class="container">
    <div class="main-banner">
      <%= render "pages/header" %>
      <div class="banner-slogan ">
        <h2 class='cursive'>Best Drink for Best Moments</h2> <br>
        <p class='cursive'>The way of enjoying your success.</p>
        <%= link_to "View Cocktails", cocktails_path, :class=> "btn btn-info" %>
      </div>
    </div>

  </div>
</div>

app/views/cocktails/_header.html.erb
<div class="header">
  <%= link_to pages_path do %>
    <%= image_tag "cocktail_logo.png", alt: "Logo", width: 30,height: 30%>
  <% end %>
  <h3>Mister Cocktail</h3>
</div>

app/views/cocktails/index.html.erb
<%= render "pages/header" %>

  <div class="container-card">
    <div class="row">
        <% @cocktails.each do |c| %>
          <div class="card" style="background-image: url(<%= asset_url('https://source.unsplash.com/250x250/?cocktail')%>)">
            <div class="card-title">
                <p id="card-name"><%= link_to c.name, cocktail_path(:cocktail), :class=> "btn btn-card" %></p>
            </div>
        </div>
        <% end %>
    </div>
  </div>

app/views/cocktails/new.html.erb
<%= render "pages/header" %>

<%= simple_form_for @cocktail do |f| %>
<%= f.input :name %>
<%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<%= render "pages/header" %>

<div class="container">
  <div class="row">
    <%= @cocktail.name %>
  </div>

  <div class="container-card">
      <div class="row">
        <% @cocktail.doses.each |dose| %>
          <%= dose.description %>
          <%= dose.ingredient %>
        <% end %>
      </div>
    </div>

   <%= link_to "Add dose", new_cocktail_path(@cocktail)%>
</div>

app/views/doses/new.html.erb
<%= simple_for_form [cocktail, dose] do |f| %>
<%=f.input :description %>
<%= f.associaton :cocktail_id %>
<%= f.association :ingredient_id%>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_header.html.erb
<div class="header">
  <%= link_to pages_path do %>
    <%= image_tag "cocktail_logo.png", alt: "Logo", width: 50,height: 50%>
  <% end %>
  <%= link_to "New Cocktail", new_cocktail_path, :class=> "btn", :id=> "btn-new" %>
</div>

app/views/pages/_home.html.erb
<div class="header">
  <%= link_to pages_path do %>
    <%= image_tag "cocktail_logo.png", alt: "Logo", width: 50,height: 50%>
  <% end %>
  <h3>Mister Cocktail</h3>
</div>

app/views/pages/home.html.erb
<div class="header">
  <%= image_tag "cocktail_logo.png", alt: "Logo", width: 50,height: 50 %>
  <h3>Mister Cocktail</h3>
</div>

<div class="main">
  <div class="main-banner">
    <%#image_tag "cocktails_sunset.jpeg", alt: "Sunset with Cocktails", :class => "banner-img"%>
    <div class="banner-slogan">
      <h2 class='cursive'>Best Drink for Best Moments</h2> <br>
      <p class='cursive'>The way of enjoying your success.</p>
      <%= link_to "View Cocktails", cocktails_path, :class=> "btn btn-info" %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="main">
  <!-- <div class="container"> -->
      <div class="col col-sm col-md col-lg col-xl">
        <div class="main-banner">
          <%=render "pages/header" %>
          <div class="banner-slogan" id="slogan-opacity">
            <h2 class='cursive'>Best Drink for Best Moments</h2> <br>
            <p class='cursive'>The way of enjoying your success.</p>
            <%= link_to "View Cocktails", cocktails_path, :class=> "btn btn-info" %>
          </div>
        </div>
      </div>
<!-- </div> -->
</div>